### ISSUE TITLE
Limited Number of Repositories shown 

### ISSUE THREAD

**Issue by barelyhuman** [MehediH/GitCleanup#1]
## Observation
The Public repos card is unable to fetch more than 15-20 repos for the logged in user.
I've got 102 public repos but only a few were shown

**Comment by MehediH** [comment]
Turns out GitHub API limits responses to 30 APIs per request, I have now updated the app to work around this problem, and you should now be able to see all your repos.  I have also added repo counts to the public/private repo sections. 

Note: you may need to re-authorise the app as I had to require the "user" scope for GitHub Auth to get a total count of how many repositories a user has. 

Please let me know if you are still facing problems!
